### ISSUE TITLE
Some questions about the article

### ISSUE THREAD

**Issue by haolyuan** [Gorilla-Lab-SCUT/LPDC-Net#1]
Thanks for your releasing! I have some questions about the part 'Cross-time Correspondence Modeling' in your article. I am confused about the associate position. Given a point p0 in initial time, how can I get the associate position pk in other time? Is the points among different time corresponding?

**Comment by tangjiapeng** [comment]
For the point sampled from dynamic surface sequence, we can know the dense correspondences between the points among different time.  Please refer to the export_pointcloud function in the scripts/sampling_mesh.py. However, if the point p0 is not lying in the suface in time t0,  we don't know the ground truth of associate position pk in other time. We just constrain that the occupancy prediction of pk should be consistent with the occupancy label of p0. In other word,  the occupancy values of points are always invariant along the temporal evolution.

**Comment by haolyuan** [comment]
Thank you for your explanation! I know that the values of f(p0) in initial time and f(pk) in k time should be consistent in part ' Cross-time Correspondence Modeling'.  However, given a point p0 in initial time, is the associate position pk in other time known in data set? In other words, is the points in the same body part sampled in different point clouds corresponding previously in data set to train the transform process g?

**Comment by tangjiapeng** [comment]
Yes! According to the  ground-truth surface mesh sequences, we can sample some point cloud trajectories.

**Comment by haolyuan** [comment]
Thanks for your explanation!

**Comment by tangjiapeng** [comment]
You are welcome! Hope I can help you.
